name: PHP CI

on: [push, pull_request]

jobs:
  install_tools:

    runs-on: ubuntu-18.04

    name: Install tools

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install tools
        uses: ngmy/phive-install-action@master
        with:
          phive-arguments: --force-accept-unsigned

      - name: Upload tools to artifact store
        uses: actions/upload-artifact@master
        with:
          name: tools
          path: tools

  build_images:

    runs-on: ubuntu-18.04

    name: Build images

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build apache2 image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          cp -f ../.laradock/docker-compose-ci.yml docker-compose.yml
          cp -f ../.laradock/env-development .env
          docker-compose build
        working-directory: laradock

      - name: Upload apache2 image to artifact store
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: laradock-ngmy-l4-dav_apache2:latest

  test:

    needs: [install_tools, build_images]

    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        php: ['7.3', '7.4', '8.0']
        deps: [highest, lowest]
        include:
          - php: '7.4'
            deps: current

    name: Test (PHP ${{ matrix.php }}, ${{ matrix.deps }} dependencies)

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up PHP ${{ matrix.php }}
        run: sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}

      - name: Configure php.ini
        run: |
          sudo sed -i \
            -e 's/zend.assertions = -1/zend.assertions = 1/' \
            -e 's/;assert.exception = On/assert.exception = On/' \
            /etc/php/${{ matrix.php }}/cli/php.ini

      - name: Update Composer to latest version
        run: sudo composer self-update

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Cache Composer packages
        if: matrix.deps == 'current'
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: |
          if [[ "${{ matrix.deps }}" == 'current' && "${{ steps.composer-cache.outputs.cache-hit }}" != 'true' ]]; then
            composer install --no-interaction
          fi
          if [[ "${{ matrix.deps }}" == 'highest' ]]; then
            composer update --no-interaction
          fi
          if [[ "${{ matrix.deps }}" == 'lowest' ]]; then
            composer update --no-interaction --prefer-lowest --prefer-stable
          fi

      - name: Download tools from artifact store
        uses: actions/download-artifact@master
        with:
          name: tools
          path: tools

      - name: Set tools as an executable
        run: find tools -type f -print0 | xargs -0 chmod +x

      - name: Download apache2 image from artifact store
        uses: ishworkh/docker-image-artifact-download@v1
        with:
          image: laradock-ngmy-l4-dav_apache2:latest

      - name: Start apache2 container
        run: |
          cp -f ../.laradock/docker-compose-ci.yml docker-compose.yml
          cp -f ../.laradock/env-development .env
          docker-compose up -d --no-build apache2
          docker-compose exec -T apache2 mkdir -p .laradock/data/apache2/var \
            .laradock/data/apache2/webdav_no_auth \
            .laradock/data/apache2/webdav_basic_auth \
            .laradock/data/apache2/webdav_digest_auth
          docker-compose exec -T apache2 chown -R www-data:www-data .laradock/data/apache2
          docker-compose exec -T apache2 htpasswd -b -c /etc/apache2/.htpasswd basic basic
          docker-compose exec -T apache2 bash -c '(echo -n "digest:Digest Auth:" && echo -n "digest:Digest Auth:digest" | md5sum - | cut -d"-" -f1 | sed "s/ *$//") > /etc/apache2/.htdigest'
        working-directory: laradock

      - name: Add /etc/hosts entry for apache2 container
        run: echo '127.0.0.1 apache2' | sudo tee -a /etc/hosts

      - name: Run lint
        env:
          PSALM_SHEPHERD: 1
          # TODO: Remove it when psalm no longer tries to create a cache directory
          #       https://github.com/vimeo/psalm/issues/4267
          XDG_CACHE_HOME: /tmp
        run: composer lint

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Run unit tests
        env:
          XDEBUG_MODE: coverage
        run: composer test

      - name: Upload coverage results to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: php tools/php-coveralls --coverage_clover=build/logs/clover.xml -v
